server:
  port: 10086
spring:
  application:
    name: tensquare-eureka
  rabbitmq:
    host: 192.168.12.145
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus‐refresh
