server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  redis:
    host: 192.168.12.145
  rabbitmq:
    host: 192.168.12.145
  data:
    mongodb:
      host: 192.168.12.145
      database: spitdb
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh      
